[package]
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
name = "query-crates-index"
version = "0.1.0"

[dependencies]
cargo = "0.24.0"
failure = "0.1.1"
walkdir = "2.0.1"
daggy = "0.5.0"
serde = "1.0.27"
serde_derive = "1.0.27"
bincode = "0.9.2"
